// Netlify Function: fetch a YouTube video's transcript with no API key.
// Strategy: load the public watch page, pull the caption track list out of
// ytInitialPlayerResponse, then fetch the track's timedtext XML and flatten
// it to plain text. This relies on YouTube's public page structure, which is
// undocumented and can change — treat failures as expected occasionally.

exports.handler = async (event) => {
  const cors = {
    'Access-Control-Allow-Origin': '*',
    'Access-Control-Allow-Headers': 'Content-Type',
    'Access-Control-Allow-Methods': 'GET, OPTIONS',
  };
  if (event.httpMethod === 'OPTIONS') return { statusCode: 200, headers: cors, body: '' };

  try {
    const videoId = (event.queryStringParameters || {}).videoId;
    if (!videoId) {
      return { statusCode: 400, headers: cors, body: JSON.stringify({ error: 'Missing videoId query param' }) };
    }

    const pageRes = await fetch(`https://www.youtube.com/watch?v=${encodeURIComponent(videoId)}`, {
      headers: {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0 Safari/537.36',
        'Accept-Language': 'en-US,en;q=0.9',
      },
    });
    if (!pageRes.ok) {
      return { statusCode: 502, headers: cors, body: JSON.stringify({ error: 'Could not load YouTube page', status: pageRes.status }) };
    }
    const html = await pageRes.text();

    const match = html.match(/"captionTracks":(\[.*?\])/);
    if (!match) {
      return { statusCode: 404, headers: cors, body: JSON.stringify({ error: 'No captions found for this video (captions may be disabled).' }) };
    }

    let tracks;
    try {
      tracks = JSON.parse(match[1]);
    } catch (e) {
      return { statusCode: 500, headers: cors, body: JSON.stringify({ error: 'Failed to parse caption track list' }) };
    }

    // Prefer a manually-created English track, then any English (incl. auto), then just the first available.
    const track =
      tracks.find((t) => t.languageCode === 'en' && t.kind !== 'asr') ||
      tracks.find((t) => t.languageCode && t.languageCode.startsWith('en')) ||
      tracks[0];

    if (!track || !track.baseUrl) {
      return { statusCode: 404, headers: cors, body: JSON.stringify({ error: 'No usable caption track found' }) };
    }

    const baseUrl = track.baseUrl.replace(/\\u0026/g, '&');
    const capRes = await fetch(baseUrl, {
      headers: { 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/124.0 Safari/537.36' },
    });
    if (!capRes.ok) {
      return { statusCode: 502, headers: cors, body: JSON.stringify({ error: 'Could not fetch caption track', status: capRes.status }) };
    }
    const xml = await capRes.text();

    const decode = (s) =>
      s
        .replace(/&#39;/g, "'")
        .replace(/&quot;/g, '"')
        .replace(/&amp;/g, '&')
        .replace(/&lt;/g, '<')
        .replace(/&gt;/g, '>');

    const lines = [...xml.matchAll(/<text[^>]*>([\s\S]*?)<\/text>/g)].map((m) => decode(m[1]).replace(/\n/g, ' ').trim());
    const transcript = lines.join(' ').replace(/\s+/g, ' ').trim();

    if (!transcript) {
      return { statusCode: 404, headers: cors, body: JSON.stringify({ error: 'Caption track was empty' }) };
    }

    return {
      statusCode: 200,
      headers: { ...cors, 'Content-Type': 'application/json' },
      body: JSON.stringify({ videoId, language: track.languageCode, autoGenerated: track.kind === 'asr', transcript }),
    };
  } catch (err) {
    return { statusCode: 500, headers: cors, body: JSON.stringify({ error: String(err && err.message || err) }) };
  }
};
